config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'articles#show'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  resources :articles
  resources :categories, except: [:destroy]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
  	has_many :article_categories
  	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end 

app/models/category.rb
class Category < ApplicationRecord
	has_many :article_categories
  	has_many :articles, through: :article_categories
	validates :name, presence:true, uniqueness:{case_sensitive: false}, length:{minimum:3, maximum:25}
	#  can also use   "validates_uniqueness_of :name"
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true,
				uniqueness:{case_sensitive: false},
				length:{minimum:3, maximum:25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
				uniqueness:{case_sensitive: false},
				length:{maximum:100},
				format:{with:VALID_EMAIL_REGEX}
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?
  def current_user
  	@current_user||=User.find(session[:user_id]) if session[:user_id]
  end
  def logged_in?
  	!!current_user
  end
  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only:[:show,:edit,:update,:destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end
	def show

	end
	def new
		@article = Article.new
	end
	def edit
		
	end
	def update
		
		if @article.update(article_params)
			flash[:notice] = "Article was updated successfully."
			redirect_to @article
		else
			render 'edit'
		end
	end
	def destroy
		
		@article.destroy
		flash[:danger] = "Article was successfully deleted"
		redirect_to articles_path
	end
	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:notice] = "Article was created successfully."
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end
	private 
	def set_article
		@article=Article.find(params[:id])
	end
	def article_params
		params.require(:article).permit(:title,:description, category_ids: [])
	end
	def require_same_user
		if current_user != @article.user
			flash[:danger] = "You can only edit or delete your own articles"
			redirect_to root_path
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except:[:index, :show]
	def index
		@categories = Category.paginate(page: params[:page], per_page:5)
	end
	def show
		@category=Category.find(params[:id])
		@category_articles = @category.articles.paginate(page: params[:page], per_page:5)

	end
	
	def new
		@category=Category.new
	end

	def create
		@category=Category.new(category_params)
		if @category.save
			flash[:success]="category created successfully"
			redirect_to categories_path
		else
			render 'new'
		end
	end
	def edit
		@category=Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			flash[:success]="category was successfully updated"
			redirect_to category_path(@category)
		else
			render 'edit'
		end
	end

	private
	def require_admin
		if !logged_in? || (logged_in? and !current_user.admin?)
			flash[:danger]="only admins can do that"
			redirect_to categories_path
		end
	end
	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to articles_path if logged_in?
	end
	def about

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	
	end
	
	def create
		user = User.find_by(email: params[:session][:email].downcase)
	    if user && user.authenticate(params[:session][:password])
	      session[:user_id] = user.id
	      flash[:notice] = "Logged in successfully"
	      redirect_to user
	    else
	      flash.now[:alert] = "There was something wrong with your login details"
	      render 'new'
	    end
	end
	
	def destroy
		session[:user_id] = nil
	    flash[:notice] = "Logged out"
	    redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]
	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id]=@user.id
			flash[:success] = "Welcome to My App #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def edit

	end

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end
	def destroy
		@user=User.find(params[:id])
		@user.destroy
		flash[:danger]="User and all articles created by user have been deleted"
		redirect_to users_path
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	private
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end

		def set_user
			@user = User.find(params[:id])
		end
		def require_same_user
			if current_user != @article.user && !current_user.admin
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
			end
		end
		def require_admin
			if logged_in? and !current_user.admin?
				flash[:danger] = "Only admin users can perform that action"
				redirect_to root_path
			end
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="page-content">
  <% obj.each do |article| %>
    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-8 mt-4">
          <div class="card text-center shadow mb-5 bg-white rounded">
            <div class="card-header font-italic">
              <div class="article-title">
                <%= link_to article.title, article_path(article) %>
              </div>
              <div class="article-body">
                <%= truncate(article.description, length: 100) %>
                <div class="article-meta-details">
                  <small>Created by: <%= article.user.username if article.user%>,
                  <%= time_ago_in_words(article.created_at) %> ago,last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
                </div>
              </div>
              <% if article.categories.any? %>
                <p> Categories: <%= render article.categories %></p>
              <% end %>
              <% if logged_in? && (current_user == article.user || current_user.admin?) %>
                <div class="article-actions">
                  <%= link_to "Edit this article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                  <%= link_to "Delete this article", article_path(article), method: :delete,data: { confirm: "Are you sure you want to delete the article?"}, class: "btn btn-xs btn-danger" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
<div class="row justify-content-center">
    <%= render 'shared/errors', obj: @article %>
    <div class="col-10">
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description of article" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <div class="row">
            <div class = "col-sm-offset-2 col-sn-8">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>
<div align="center">
  <%= will_paginate %>
</div>
<%= render 'article', obj: @articles %>
<div align="center">
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div id="page-content">
  <h1 class="text-center mt-4">Create a new article</h1>
  <%= render 'form' %>
</div> 

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
  <div class="container">
    <div class="row justify-content-center">
      <div class="well col-xs-8 col-xs-offset-2">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <% if @article.user %>
            <ul class="listing">
              <div class="row center">
                <div class="col-md-4 col-md-offset-4">
                  <p>Created by:</p>
                  <p><%= link_to gravatar_for(@article.user), user_path(@article.user) %></p>
                  <p class="article-title">
                    <%= link_to @article.user.username, user_path(@article.user) %>
                  </p>
                  <p><small>
                    <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
                  </small></p>
                </div>
              </div>
            </ul>
          <% end %>
          <h4 class="center description"><strong>Description:</strong></h4>
          <hr>
          <%= simple_format(@article.description) %>
          <% if @article.categories.any? %>
            <p>Categories: <%= render @article.categories %></p>
          <% end %>
          <div class="article-actions">
            <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
              <%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
              <%= link_to "Delete this article", article_path(@article), method: :delete, 
                                                data: { confirm: "Are you sure you want to delete the article?"}, 
                                                class: "btn btn-xs btn-danger" %>
            <% end %>
            <%= link_to "View all articles", articles_path, class: "btn btn-xs btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category) %> &nbsp:</span>

app/views/categories/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a category" %>
          </div>
        </div>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 

app/views/categories/edit.html.erb
<h1 align="center"> Edit Category</h1>
<%= render 'form' %>

app/views/categories/index.html.erb
<h1 align="center">Listing All Categories</h1>
<div align="center">
  <%= will_paginate %>
  <% @categories.each do |category| %>
    <ul class="listing">
      <div class="row">
        <div class="well col-md-4 col-md-offset-4">
          <p class="article-title">
            <%= link_to "#{category.name}", category_path(category) %>
          </p>
          <p><small><%= pluralize(category.articles.count, "article") %></small></p>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/categories/new.html.erb
<h1 align="center"> Create New Categories</h1>
<%= render 'form' %>

app/views/categories/show.html.erb
<h1 align="center"><% "Category: " + @category.name %></h1>
<div align="center">
	<% if logged_in? and current_user.admin? %>
		<span class="badge">
			<%= link_to "Edit category name", edit_category_path(@category) %>
		</span>
	<% end %>
  	<%= will_paginate @category_articles%>
</div>
<%= render 'articles/article', obj: @category_articles %>
<div align="center">
  <%= will_paginate @category_articles%>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Rohit Gaur</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div> 

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "MY APP", root_path, class:"navbar-brand",id:"logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--<li class="nav-item active">
        <%= link_to "Articles",articles_path, class:"nav-link" %>
      </li> -->
      <li class="nav-item">
        <%= link_to "Bloggers", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Articles
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Create New Article", new_article_path,class:"dropdown-item" %>
            <%= link_to "View Articles", articles_path,class:"dropdown-item" %>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "All Categories", categories_path ,class:"dropdown-item"%>
            <% Category.all.each do |category| %>
              <%= link_to "#{category.name}", category_path(category),class:"dropdown-item" %>
            <% end %>
            <% if logged_in? and current_user.admin? %>
              <%= link_to "Create New Category", new_category_path ,class:"dropdown-item"%>
            <% end %>
          </div>
        </li>
    </ul>
    <ul class="nav navbar-nav navbar-right" margin="auto">
      <% if logged_in? %>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= "Admin" if current_user.admin? %> Profile</a>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
            <%= link_to "Edit your profile", edit_user_path(current_user), class:"dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user), class:"dropdown-item" %>
          </div>
        </li>

      <li class="nav-item">
        <%= link_to "Log out", logout_path, method: :delete, class: "nav-link" %>
      </li>
      
      <% else %>
      <li class="nav-item">
        <li><%= link_to 'Log in', login_path, class: "nav-link" %></li>
        <li><%= link_to 'Sign up', signup_path, class: "nav-link" %></li>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <%= csrf_meta_tags %>

  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> this is about page </h1>

<p><%= link_to 'return to articles listing', articles_path %></p>
<p><%= link_to 'create new articles listing', new_article_path %></p>
<p><%= link_to 'Home', root_path %></p>

app/views/pages/home.html.erb
<div class="center jumbotron">
    <div class="jumbotron text-center text-black">
	    <h1 class="display-4">My App</h1>
	    <hr class="my-4">
	    <%= link_to "Sign up now", signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %> 

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
    </div>
    <div class="mb-3">
      <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
</div> 

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your Profile</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">MyApp Bloggers</h1>

<div class="flickr_pagination">
  <%= will_paginate @users, :container => false %>
</div>

<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%= link_to user.username, user %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= link_to gravatar_for(user, size: 150), user %>
            </h5>
            <p class="card-text"><%= pluralize(user.articles.count, "article") if user.articles %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? and (current_user.admin? || user==current_user) %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
            <% if logged_in? and current_user.admin? %>
            <%= link_to "Delete this user", user_path(user), method: :delete, data: { confirm: "Are you sure you want to delete the user and all their articles?"}, class: "btn btn-outline-danger"  %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for my App</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @user, size: 150 %>
  </div>
</div>
<h4 align="center"><%= @user.username %>'s articles</h4>
<div class="center">
  <%= will_paginate @user_articles %>
</div>
<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>